### ISSUE TITLE
requires full width

### ISSUE THREAD

**Issue by willadsen** [HHuckebein/HorizontalPicker#1]
On iPad, if the picker's width is not equal to the full width of the iPad, the values go outside the width. Seems like it's not designed to be used in anything else than full width for the device - which obviously doesn't work
![ios simulator screen shot 09 12 2013 12 14 18](https://f.cloud.github.com/assets/418766/1704135/136672ba-60c3-11e3-98e1-a10d667771cb.png)

**Comment by jamieomatthews** [comment]
This hasn't been my experience.  Maybe the component has been updated since you've posted but If I drop a UIView onto XIB and set the files owner as the HorizontalScrollView it seems to work just fine

**Comment by isair** [comment]
I also have this problem. My code is as follows:

```
self.showtimeHourPicker = [HorizontalPickerView alloc];
self.showtimeHourPicker.delegate = self;
self.showtimeHourPicker.dataSource = self;
self.showtimeHourPicker.style = HPStyle_iOS7;
self.showtimeHourPicker = [self.showtimeHourPicker initWithFrame:CGRectMake(0, 173, 332, 45)];
[showtimesContainer addSubview:self.showtimeHourPicker];
```

Edit: It looks like cocoapods downloads an older version of this library, I manually added it and it worked.
