### ISSUE TITLE
Demo project does not compile

### ISSUE THREAD

**Issue by ivanzoid** [HHuckebein/HorizontalPicker#4]
I'm trying with "pod try HorizontalPicker", and get the following error in HPDemo-Prefix.pch:
# import <HorizontalPickerView/HorizontalPickerView.h>

fatal error: 'HorizontalPickerView/HorizontalPickerView.h' file not found

**Comment by rubencodes** [comment]
I just downloaded the demo and tried running it in xcode and got the same error.

**Comment by Voidozzer** [comment]
+1

**Comment by broderick99** [comment]
+1
