### ISSUE TITLE
zombies rearing their ugly head

### ISSUE THREAD

**Issue by raytrask** [HHuckebein/HorizontalPicker#6]
Love the picker, it is easily the best looking one out there!

That said, it seems like I can setup HorizontalPicker fine in some situations.  But when I setup a navigation controller and pop back to the root Controller after displaying controller that contains a HorizontalPicker, I get an illegal zombie access.   Has anyone used HorizontalPicker deep into a navigation controller stack and back?. 

2014-11-25 21:18:32.777 HPickerPlay[27868:3110602] **\* -[UICollectionView delegate]: message sent to deallocated instance 0x7d398600
(lldb) 

Full screen dump of error here... http://screencast.com/t/WoY28qFeCMcb

Small sample app producing the error at...  https://www.dropbox.com/s/r3rvvrbgfil1fr9/HPickerPlay.zip?dl=0

**Comment by szemian** [comment]
I was attacked by the same zombies, specifically only in iOS 8. 

My workaround is to add collectionController **view** instead of **collectionView** as subview of HorizontalPickerView in **prepareForAppearance** as follow:

``` objective-c
- (void)prepareForAppearance
{
    _isInitialized = TRUE;

    self.backgroundColor = _style == HPStyle_iOS7 ? [UIColor clearColor] : [UIColor blackColor];

    CGRect gradientRect = CGRectInset(self.bounds, kTopFrameXOffset, kTopFrameYOffset);

    // adjust frame of collectionController view
    CGRect adjustedViewFrame = self.collectionController.view.frame;
    adjustedViewFrame.origin = CGPointMake(0, 0);
    self.collectionController.view.frame = adjustedViewFrame;

    if (_style == HPStyle_iOS7) {
        [self.layer addSublayer:self.shapeLayer];
        [self addSubview:self.collectionController.view];
    }
    else {
        [self addSubview:[[HPWhiteGradientView alloc] initWithFrame:gradientRect]];
        [self addSubview:[[HPBlackGradientView alloc] initWithFrame:gradientRect]];
        [self addSubview:self.collectionController.view];
        [self addSubview:self.topFrameView];
    }
}
```

Not sure if this is the best solution, but it keeps the zombies away, for now.

**Comment by raytrask** [comment]
I'm definitely using iOS 8.  I'll check it out.
Thanks

**Comment by raytrask** [comment]
There is definitely a bug when running in 8.1.   I changed the simulator to run in 7.1 and did not get the error!

However,  I added the code above and it did not work for me.  Here is my code directly cut from XCode.  Am I missing something?

``` objectivec
- (void)prepareForAppearance
      {
    _isInitialized = TRUE;

    self.backgroundColor = _style == HPStyle_iOS7 ? [UIColor clearColor] : [UIColor blackColor];

    CGRect gradientRect = CGRectInset(self.bounds, kTopFrameXOffset, kTopFrameYOffset);

    // adjust frame of collectionController view

    CGRect adjustedViewFrame = self.collectionController.view.frame;
    adjustedViewFrame.origin = CGPointMake(0, 0);
    self.collectionController.view.frame = adjustedViewFrame;


    if (_style == HPStyle_iOS7) {
        [self.layer addSublayer:self.shapeLayer];
        [self addSubview:self.collectionController.collectionView];
    }
    else {
        [self addSubview:[[HPWhiteGradientView alloc] initWithFrame:gradientRect]];
        [self addSubview:[[HPBlackGradientView alloc] initWithFrame:gradientRect]];
        [self addSubview:self.collectionController.collectionView];
        [self addSubview:self.topFrameView];
    }
}
```

**Comment by szemian** [comment]
You have to replace the following line (in both if and else cases):

**[self addSubview:self.collectionController.collectionView];**
to
**[self addSubview:self.collectionController.view];**

**Comment by raytrask** [comment]
That was it!  I'm glad it was pilot error.  Those are the easiest to fix.   

Do you understand why that fixed the problem?  Should that be something to submit for a permanent fix?

**Comment by dturnq** [comment]
That was really helpful, szemian! To any future readers: Make sure to also include the 3 lines after `// adjust frame of collectionController view`. That briefly tripped me up for a bit.

Thanks!

**Comment by altyus** [comment]
Hey Guys, 

I had the same issue and had the same fix.  Any reason not to get this up in a PR? (I'm willing to submit)

**Comment by nalexn** [comment]
The fix suggested by @szemian fixes the crash, although this introduces a layout issue if you're using auto-layout.
A quickly found workaround was to subclass the HorizontalPickerView and in -(void)dealloc iterate through its subviews and invoke removeFromSuperview for each subview.
